import type { Metadata } from "next";
import "./globalStyles/globals.scss";
import "./globalStyles/header.scss";
import "./globalStyles/menu.scss";
import "./globalStyles/mobile-navbar.scss";
import "./globalStyles/search-modal.scss";
import "./globalStyles/footer.scss";
import "./globalStyles/hero.scss";
import "./globalStyles/main-page.scss";
import "./globalStyles/cart-popup.scss";
import './globalStyles/normalize.scss'
import { Layout } from "./components/layouts/Layout";





export const metadata: Metadata = {
  title: "E-SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
