  export const collectionItems = [
    {
      id: 1,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection1.svg',
      price: 10045,
    },
    {
      id: 2,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 3,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection3.svg',
      price: 10045,
    },
    {
      id: 4,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 5,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 6,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 7,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 8,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 9,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 10,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 11,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 12,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 13,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 14,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 15,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 16,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 1,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection1.svg',
      price: 10045,
    },
    {
      id: 2,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 3,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection3.svg',
      price: 10045,
    },
    {
      id: 4,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 5,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 6,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 7,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 8,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 9,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 10,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 11,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 12,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 13,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 14,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 15,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
    {
      id: 16,
      title: 'Кожа крокодила',
      name: 'Мюли Himalaya',
      img: '/img/collections/Collection2.svg',
      price: 10045,
    },
  ];